[project]
name = "reflection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.3.0",
    "google-adk>=1.15.1",
    "openai>=2.2.0",
    "pytest>=8.4.2",
]
